CREATE TABLE "recipe" (
                          "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          "title" varchar,
                          "description" varchar,
                          "date" varchar
);

CREATE TABLE "user" (
                        "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        "name" varchar,
                        "login" varchar,
                        "password" varchar
);

CREATE TABLE "ingredient" (
                              "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              "name" varchar,
                              "calories" int
);

CREATE TABLE "recipe_ingredient" (
                                    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     "recipe" int,
                                     "ingredient" int
);
