CREATE TABLE "recipe" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "description" varchar,
  "date" datetime,
  "id_user" int,
  PRIMARY KEY ("id")
);

CREATE TABLE "user" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "login" varchar,
  "password" varchar
);

CREATE TABLE "ingredient" (
  "id" int,
  "name" varchar,
  "calories" int
);

CREATE TABLE "recipe_ingredient" (
  "id_recipe" int,
  "id_ingredient" int
);

ALTER TABLE "recipe" ADD FOREIGN KEY ("id_user") REFERENCES "user" ("id");

ALTER TABLE "recipe_ingredient" ADD FOREIGN KEY ("id_recipe") REFERENCES "recipe" ("id");

ALTER TABLE "ingredient" ADD FOREIGN KEY ("id") REFERENCES "recipe_ingredient" ("id_ingredient");
